name: Installation

on:
  push:
    branches: [ "main", "release"]
    paths:
      - '.github/workflows/install.yml'
      - 'src/**'
      - 'Makefile'
  pull_request:
    branches: [ "main", "release"]
    paths:
      - '.github/workflows/install.yml'
      - 'src/**'
      - 'Makefile'

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Local install checking
      run: make install

    - name: PYPI install checking
      run: pip install python3-anticaptcha
