name: Test Build

on:
  push:
    branches: [ "main", "release"]
    paths:
      - '.github/workflows/test_build.yml'
      - 'src/**'
      - 'Makefile'
  pull_request:
    branches: [ "main", "release"]
    paths:
      - '.github/workflows/test_build.yml'
      - 'src/**'
      - 'Makefile'

jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Local build checking
      run: |
        pip install twine wheel
        cd src/ && python setup.py sdist bdist_wheel
